### ISSUE TITLE
Component “light-dark-switch” prompts “file not found”, causing the page to load slowly

### ISSUE THREAD

**Issue by TeaEwan** [codyhouse/codyframe#4]
Component url: https://codyhouse.co/ds/components/app/light-dark-switch

Image:

<img width="1440" alt="image" src="https://github.com/codyhouse/codyframe/assets/93706123/3b8d437d-9d84-4336-a554-4da5383e51ed">

**Comment by claudia-romano** [comment]
Hi there, 
the component comes with the option to modify the custom  dropdown; for this reason, the `.ld-switch-popover__option` element includes an image that is set dynamically:
```
<figure class="radius-md inner-glow">
  <img class="radius-inherit" src="../../../app/assets/img/{option-theme-preview}" alt="Theme preview">
</figure>
``` 

You can create a placeholder image and name it `{option-theme-preview}` in order to remove the 404. That will fix your issue.

**Comment by TeaEwan** [comment]
It's working. Thank you.
