### ISSUE TITLE
Prefix not applied to all classes

### ISSUE THREAD

**Issue by rpisarew** [codyhouse/codyframe#6]
Dear Codyhouse Team,

the configurable prefix does not apply to all classes like `text-component`, `form-control`, `form-label` and `form-legend`.
Is that intentional?

**Comment by sebastiano-guerriero** [comment]
Hi! Yes, it's intentional. The reason being: we consider the typography, buttons, forms, icons scss files as templates to be copied and modified 'locally'. The reset and utility classes, on the other hand, could be imported from the node module (in case we add new utility classes, you can update the module).

```scss
@import 'https://unpkg.com/codyframe/main/css/reset.css'; /* ← reset */

/* ↓ copy these templates from Github & modify them locally */
@import 'typography.css';
@import 'icons.css';
@import 'buttons.css';
@import 'forms.css';

/* ↓ import here the CodyHouse components */
@import 'components/_1_header.css';
@import 'components/_1_footer.css';
/* ... */

@import 'https://unpkg.com/codyframe/main/css/util.css'; /* ← utility classes */
```
